package main

import (
	"fmt"
)

/*
   |    1         2         3         4         5         6
---+---------+---------+---------+---------+---------+---------+
 1 | 20151125  18749137  17289845  30943339  10071777  33511524
 2 | 31916031  21629792  16929656   7726640  15514188   4041754
 3 | 16080970   8057251   1601130   7981243  11661866  16474243
 4 | 24592653  32451966  21345942   9380097  10600672  31527494
 5 |    77061  17552253  28094349   6899651   9250759  31663883
 6 | 33071741   6796745  25397450  24659492   1534922  27995004

The first code is 20151125. After that, each code is generated by taking the previous one, multiplying it by 252533, and then keeping the remainder from dividing that value by 33554393.
*/

func main() {
	targetR := 2978
	targetC := 3083
	r := 1
	c := 1
	curr := 20151125
	for !(r == targetR && c == targetC) {
		if r == 1 {
			r = c + 1
			c = 1
		} else {
			r -= 1
			c += 1
		}
		curr = (curr * 252533) % 33554393
	}
	fmt.Printf("Value: %d", curr)
}
